### Before

In [186]:
import pandas as pd

def preprocess(file):
    dct = {}
    data = pd.read_excel(file)
    col = list(data.columns)
    for i in range(len(col)):
        atr = list(data[col[i]])
        for grade in range(len(atr)):
            if pd.isna(atr[grade]) == False:
                cls = atr[grade].split('/')
                num, nme = str(i+1) + str(grade+1) + cls[1], col[i] + '/' + cls[0]
                dct[num] = nme

    lst = [[i for i in list(dct.keys()) if int(i[1]) == len(atr) - n] for n in range(len(atr))] 
    return lst, dct

serial, lecture = preprocess('/mnt/c/Users/MLKU/Lecture/swtk/Timetable/lecture.xlsx')

def search(lst):
    for grade in range(len(lst)):
        def cycle(grade):
            flag = False
            try:
                for i in range(len(lst[grade-1])):
                    if lst[grade-1][i][0] == lst[grade][i][0]:
                        flag = True
            except:
                pass

            if flag == False:
                return
            else:
                lst[grade].append(lst[grade].pop(0))
                cycle(grade)
            
        if grade > 0:
            cycle(grade)


search(serial)
serial

[['1330', '2330', '3330', '4330', '5330'],
 ['2230', '3230', '5230', '6230', '1230'],
 ['4130', '5130', '6130', '3130']]

In [1]:
import pandas as pd
import time 

class calc:
    def preprocess(file):
        dct = {}
        data = pd.read_excel(file)
        col = list(data.columns)
        for i in range(len(col)):
            atr = list(data[col[i]])
            for grade in range(len(atr)):
                if pd.isna(atr[grade]) == False:
                    cls = atr[grade].split('/')
                    num, nme = str(i+1) + str(grade+1) + cls[1], col[i] + '/' + cls[0]
                    dct[num] = nme

        lst_all = []
        for n in range(len(atr)):
            lst_each = []
            for i in list(dct.keys()):
                if int(i[1]) == n + 1:
                    lst_each.append(i)
            if len(lst_each) < 5:
                lst_each += ['0000'] * 5 - len(lst_each)
            lst_all.append(lst_each)
            
        return lst_all, dct|{'0000':'NAN'}

    def search(lst, num):
        flag = False
        if num > 5: num = 0
        for st in list(map(list, zip(*lst))):
            if len(set([i[0] for i in st])) < len(lst):
                flag = True
                break
        if flag == False:
            return
        
        for i in range(len(lst)):
            where = i - num
            if i % 2 == 0:
                lst[i].insert(where, lst[i].pop())
            else:
                lst[i].append(lst[i].pop(where))
        search(lst, num + 1)

serial, lecture = preprocess('/mnt/c/Users/MLKU/Lecture/swtk/Timetable/lecture.xlsx')
search(serial, 0)
serial

NameError: name 'preprocess' is not defined

In [1]:
import pandas as pd

def preprocess(file):
    # 파일 읽고 일련번호 붙히기
    dct = {}
    data = pd.read_excel(file)
    col = list(data.columns)
    for i in range(len(col)):
        atr = list(data[col[i]])
        for grade in range(len(atr)):
            if pd.isna(atr[grade]) == False:
                cls = atr[grade].split('/')
                num, nme = str(i+1) + str(grade+1) + cls[1], col[i] + '/' + cls[0]
                dct[num] = nme

    # 리스트 3행으로 만들기 - len(5)이하에 값 추가
    lst_all = []
    for n in range(len(atr)):
        lst_each = []
        for i in list(dct.keys()):
            if int(i[1]) == n + 1:
                lst_each.append(i)
        if len(lst_each) < 5:
            lst_each += ['0000'] * (5 - len(lst_each))
        lst_all.append(lst_each)
        
    return lst_all, dct|{'0000':'NAN'}

def search(lst, num):
    # 교수의 중복 시간점유 확인
    flag = False
    if num > 5: num = 0
    for st in list(map(list, zip(*lst))):
        if len(set([i[0] for i in st])) < len(lst):
            flag = True
            break
    # 결과값 반환
    if flag == False:
        return lst
    # 재귀호출
    for i in range(len(lst)):
        where = i - num
        if i % 2 == 0:
            lst[i].insert(where, lst[i].pop())
        else:
            lst[i].append(lst[i].pop(where))
    search(lst, num + 1)

serial, lecture = preprocess('/mnt/c/Users/MLKU/Lecture/swtk/Table/lecture.xlsx')
search(serial, 0)


serial

[['0000', '3130', '4130', '6130', '5130'],
 ['3230', '5230', '6230', '2230', '1230'],
 ['1330', '4330', '2330', '5330', '3330']]

In [5]:
lab = [[['0000' for i in range(18)] for s in range(5)] for l in range(3)]
for t in range(3):
    cnt = 0
    for g in serial[t]:
        cnt += 1
        if not int(g) == 0:
            if cnt <= 2:
                lab[t][cnt - 1][8:11] = [g] * (int(g[2:])//5//2)
                lab[t][cnt + 1][11:14] = [g] * 3
            elif cnt <= 4:
                lab[t][cnt - 3][0:3] = [g] * 3
                lab[t][cnt - 1][3:6] = [g] * 3
            else:
                lab[t][2][0:3] = [g] * 3
                lab[t][4][3:6] = [g] * 3

# pprint.pprint(lab, width=300)
for k in range(len(lab)):
    for y in range(len(lab[k])):
        for x in range(len(lab[k][y])):
            lab[k][y][x] = lecture[lab[k][y][x]]

# pprint.pprint(lab, width=300)
df = pd.DataFrame(lab[1])
df.T

              0            1            2            3         4
0     이근호/서비스러닝      고선우/딥러닝     권수태/기계학습          NAN       NAN
1     이근호/서비스러닝      고선우/딥러닝     권수태/기계학습          NAN       NAN
2     이근호/서비스러닝      고선우/딥러닝     권수태/기계학습          NAN       NAN
3           NAN          NAN    이근호/서비스러닝      고선우/딥러닝  권수태/기계학습
4           NAN          NAN    이근호/서비스러닝      고선우/딥러닝  권수태/기계학습
5           NAN          NAN    이근호/서비스러닝      고선우/딥러닝  권수태/기계학습
6           NAN          NAN          NAN          NAN       NAN
7           NAN          NAN          NAN          NAN       NAN
8   김영수/리눅스운영체제  송주환/논리적문제해결          NAN          NAN       NAN
9   김영수/리눅스운영체제  송주환/논리적문제해결          NAN          NAN       NAN
10  김영수/리눅스운영체제  송주환/논리적문제해결          NAN          NAN       NAN
11          NAN          NAN  김영수/리눅스운영체제  송주환/논리적문제해결       NAN
12          NAN          NAN  김영수/리눅스운영체제  송주환/논리적문제해결       NAN
13          NAN          NAN  김영수/리눅스운영체제  송주환/논리적문제해결       NAN
14          NAN          NAN          NAN          NAN       NAN
15          NAN          NAN          NAN          NAN       NAN
16          NAN          NAN          NAN          NAN       NAN
17          NAN          NAN          NAN          NAN       NAN

### Main

In [1]:
import pandas as pd

def preprocess(file):
    dct = {}
    data = pd.read_excel(file)
    col = list(data.columns)
    for i in range(len(col)):
        atr = list(data[col[i]])
        for grade in range(len(atr)):
            if pd.isna(atr[grade]) == False:
                cls = atr[grade].split('/')
                num, nme = str(i+1) + str(grade+1) + cls[1], col[i] + '/' + cls[0]
                dct[num] = nme

    return list(dct.keys()), dct, grade + 1

def search(serial, grade, num):
    temp = []
    for i in range(grade):
        for n in range(len(serial)):
            if int(serial[n][1]) == i+1 and serial[n][0] not in [h[0] for h in temp]:
                temp.append(serial.pop(n))
                break
            if n == len(serial) - 1:
                temp.append('0000')
    lst_result.append(temp)
    if num == 1:
        return
    search(serial, grade, num-1)


lst_serial, dct_lecture, grade = preprocess('/mnt/c/Users/MLKU/Lecture/swtk/Timetable/lecture.xlsx')

lst_result = []
search(lst_serial, grade, 5)
lst_result = list(map(list, zip(*lst_result)))

lst_result

[['3130', '4130', '5130', '6130', '0000'],
 ['1230', '2230', '3230', '5230', '6230'],
 ['2330', '1330', '4330', '3330', '5330']]

In [3]:
import pandas as pd
import time

def preprocess(file):
    dct = {}
    data = pd.read_excel(file)
    col = list(data.columns)
    for i in range(len(col)):
        atr = list(data[col[i]])
        for grade in range(len(atr)):
            if pd.isna(atr[grade]) == False:
                cls = atr[grade].split('/')
                num, nme = str(i+1) + str(grade+1) + cls[1], col[i] + '/' + cls[0]
                dct[num] = nme

    return list(dct.keys()), dct, grade + 1


lst_result = []
def search(serial, grade, num):
    temp = []
    for i in range(grade):
        for n in range(len(serial)):
            if int(serial[n][1]) == i+1 and serial[n][0] not in [h[0] for h in temp]:
                temp.append(serial.pop(n))
                break
            if n == len(serial) - 1:
                temp.append('0000')
    lst_result.append(temp)
    if num == 1:
        return
    search(serial, grade, num-1)


lst_serial, dct_lecture, grade = preprocess('/mnt/c/Users/MLKU/Lecture/swtk/Table/lecture.xlsx')

search(lst_serial, grade, 5)

lst_result

[['1155', '2230', '3330'],
 ['3130', '1230', '2330'],
 ['4130', '3230', '1330'],
 ['5130', '6230', '4330'],
 ['6130', '5230', '0000']]

In [86]:
import pandas as pd
import time

def preprocess(file):
    dct = {}
    data = pd.read_excel(file)
    col = list(data.columns)
    for i in range(len(col)):
        atr = list(data[col[i]])
        for grade in range(len(atr)):
            if pd.isna(atr[grade]) == False:
                cls = atr[grade].split('/')
                num, nme = str(i+1) + str(grade+1) + cls[1], col[i] + '/' + cls[0]
                dct[num] = nme

    return list(dct.keys()), dct, grade + 1


lst_result = []
def search(serial, grade, num):
    if num > len(serial):
        num = 0

    if len(lst_result) == 5:
        return 
    
    temp = []
    for i in range(grade):
        for n in range(len(serial)):
            jk = n+num
            if jk > len(serial) or jk < -len(serial):
                jk = len(serial) - (jk - len(serial))
            atr = serial[n-num]
            if int(serial[jk][1]) == i+1 and serial[jk][0] not in [h[0] for h in temp]:
                temp.append(serial.pop(jk))
                break
    if len(temp) == grade:
        lst_result.append(temp)
        search(serial, grade, num+1)
    else:
        serial.extend(lst_result.pop())
        search(serial, grade, num+1)
        

        



    


lst_serial, dct_lecture, grade = preprocess('/mnt/c/Users/MLKU/Lecture/swtk/Table/lecture.xlsx')
search(lst_serial, grade, 0)

lst_result,lst_serial

IndexError: list index out of range

In [34]:
last = []
lst_result = []

def 


def search(serial, grade, last):
    

    if len(serial) == 0:
        return 

    temp = []
    for i in range(grade):
        for n in range(len(serial)):
            if int(serial[n][1]) == i+1 and serial[n][0] not in [h[0] for h in temp] and serial[n] not in last:
                temp.append(serial.pop(n))
                break

    lst_result.append(temp)
    print(temp)

    # if len(lst_result[-1]) < 3:
    #     last = lst_result.pop()
    #     serial.extend(last)

    #     search(serial, grade, last)

lst_serial, dct_lecture, grade = preprocess('/mnt/c/Users/MLKU/Lecture/swtk/Table/lecture.xlsx')
search(lst_serial, grade, last)

lst_result, lst_serial, last

['1155', '2230', '3330']

([['1155', '2230', '3330']],
 ['1230',
  '1330',
  '2330',
  '3130',
  '3230',
  '4130',
  '4330',
  '5130',
  '5230',
  '5330',
  '6130',
  '6230'],
 [])

In [17]:
N, M = 4,3
ans = []

def back():
    if len(ans) == M: # 배열의 길이를 확인
        print(" ".join(map(str, ans))) # 1 2 3 이런 상태로 출력하기 위해
        return 
    for i in range(1, N+1): # 1 ~ N 까지
        if i not in ans: # 중복 확인
            ans.append(i) # 배열 추가
            back() # 재귀
            ans.pop() # return으로 돌아오면 이게 실행됨. 1, 2, 3 일때 3을 없앰으로 전 단계로 돌아가는 것
            
back()

1 2 3
1 2 4
1 3 2
1 3 4
1 4 2
1 4 3
2 1 3
2 1 4
2 3 1
2 3 4
2 4 1
2 4 3
3 1 2
3 1 4
3 2 1
3 2 4
3 4 1
3 4 2
4 1 2
4 1 3
4 2 1
4 2 3
4 3 1
4 3 2

In [311]:
lst_serial, dct_lecture, grade = preprocess('/mnt/c/Users/MLKU/Lecture/swtk/Timetable/lecture.xlsx')
lst_result = []
search(lst_serial, grade, 5)

lst_n = []
for i in range(len(lst_result)):
    son = lst_result[i][:2]
    num = int(lst_result[i][2:])
    a,b = divmod(num, 15)

    if num == 0:
        lst_result[i] = [lst_result[i]] * 2
    elif b == 0:
        lst_result[i] = [son + str(num//a)] * 2
    else:
        lst_result[i] = [son + str(num//a), son + str(b)] 
lst_result

2 0
2 0
2 0
2 0
2 0
2 0
2 0
2 0
2 0
2 0
2 0
2 0
0 0
2 0
2 0

[['3115', '3115'],
 ['1215', '1215'],
 ['2315', '2315'],
 ['4115', '4115'],
 ['2215', '2215'],
 ['1315', '1315'],
 ['5115', '5115'],
 ['3215', '3215'],
 ['4315', '4315'],
 ['6115', '6115'],
 ['5215', '5215'],
 ['3315', '3315'],
 ['0000', '0000'],
 ['6215', '6215'],
 ['5315', '5315']]

In [376]:
lab = [[['0000' for i in range(18)] for s in range(5)] for l in range(3)]

def back(lst, grade):

    # 코드 작성 - 3학년부터 읽어옴
    if len(lab) == grade + 1:
        pass
    else:
        pass
    
    if grade == 0:
        return 
    back(lst, grade - 1)

back(serial, len(serial)-1)

['1330', '4330', '2330', '5330', '3330']
['3230', '5230', '6230', '2230', '1230']
['0000', '3130', '4130', '6130', '5130']

In [235]:
import pprint
lab = [[['0000' for i in range(18)] for s in range(5)] for l in range(3)]
for t in range(len(serial)):
    cnt = 0
    for g in range(len(serial[t])):

        if not int(serial[t][g]) == 0:
            if g <= 1:
                r = lab[t][g][8:14]
                for h in r:
                    if not int(h) == 0:
                        o = False
                lab[t][g][8:14] = [serial[t][g]] * (int(serial[t][g][2:])//5)
                
            else:
                lab[t][g-2][0:6] = [serial[t][g]] * (int(serial[t][g][2:])//5)



for k in range(len(lab)):
    for y in range(len(lab[k])):
        for x in range(len(lab[k][y])):
            lab[k][y][x] = lecture[lab[k][y][x]]

# pprint.pprint(lab, width=300)
df = pd.DataFrame(lab[0])
df.T

KeyError: '0000'

In [5]:
import pprint
lab = [[['0000' for i in range(18)] for s in range(5)] for l in range(3)]
for t in range(3):
    cnt = 0
    for g in lst_result[t]:
        cnt += 1
        if not int(g) == 0:
            if cnt <= 2:
                lab[t][cnt - 1][8:11] = [g] * (int(g[2:])//5//2)
                lab[t][cnt + 1][11:14] = [g] * 3
            elif cnt <= 4:
                lab[t][cnt - 3][0:3] = [g] * 3
                lab[t][cnt - 1][3:6] = [g] * 3
            else:
                lab[t][2][0:3] = [g] * 3
                lab[t][4][3:6] = [g] * 3

# pprint.pprint(lab, width=300)
for k in range(len(lab)):
    for y in range(len(lab[k])):
        for x in range(len(lab[k][y])):
            lab[k][y][x] = lecture[lab[k][y][x]]

# pprint.pprint(lab, width=300)
df = pd.DataFrame(lab[2])
df.T

NameError: name 'lecture' is not defined

In [137]:
import pprint
lab = [[['____' for i in range(18)] for s in range(5)] for l in range(3)]
for t in range(3):
    cnt = 0
    for g in serial[t]:
        cnt += 1
        if not int(g) == 0:
            if cnt <= 2:
                lab[t][cnt - 1][8:11] = [g] * (int(g[2:])//5//2)
                lab[t][cnt + 1][11:14] = [g] * 3
            elif cnt <= 4:
                lab[t][cnt - 3][0:3] = [g] * 3
                lab[t][cnt - 1][3:6] = [g] * 3
            else:
                lab[t][2][0:3] = [g] * 3
                lab[t][4][3:6] = [g] * 3

pprint.pprint(lab, width=300)

[[['4130', '4130', '4130', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____'],
  ['6130', '6130', '6130', '____', '____', '____', '____', '____', '3130', '3130', '3130', '____', '____', '____', '____', '____', '____', '____'],
  ['5130', '5130', '5130', '4130', '4130', '4130', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____'],
  ['____', '____', '____', '6130', '6130', '6130', '____', '____', '____', '____', '____', '3130', '3130', '3130', '____', '____', '____', '____'],
  ['____', '____', '____', '5130', '5130', '5130', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____']],
 [['6230', '6230', '6230', '____', '____', '____', '____', '____', '3230', '3230', '3230', '____', '____', '____', '____', '____', '____', '____'],
  ['2230', '2230', '2230', '____', '____', '____', '____', '____', '5230', '5230', '5230', '____', '____', '____', '____', '____', '____', '____'],
  ['1230', '1230', '1230', '6230', '6230', '6230', '____', '____', '____', '____', '____', '3230', '3230', '3230', '____', '____', '____', '____'],
  ['____', '____', '____', '2230', '2230', '2230', '____', '____', '____', '____', '____', '5230', '5230', '5230', '____', '____', '____', '____'],
  ['____', '____', '____', '1230', '1230', '1230', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____']],
 [['2330', '2330', '2330', '____', '____', '____', '____', '____', '1330', '1330', '1330', '____', '____', '____', '____', '____', '____', '____'],
  ['5330', '5330', '5330', '____', '____', '____', '____', '____', '4330', '4330', '4330', '____', '____', '____', '____', '____', '____', '____'],
  ['3330', '3330', '3330', '2330', '2330', '2330', '____', '____', '____', '____', '____', '1330', '1330', '1330', '____', '____', '____', '____'],
  ['____', '____', '____', '5330', '5330', '5330', '____', '____', '____', '____', '____', '4330', '4330', '4330', '____', '____', '____', '____'],
  ['____', '____', '____', '3330', '3330', '3330', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____', '____']]]

In [ ]:
/mnt/c/Users/MLKU/Lecture/swtk/Table/rooms.xlsx

In [283]:
rooms = pd.read_excel('./rooms.xlsx', sheet_name=['1학년', '2학년', '3학년'])
rooms

dn = rooms['1학년'].fillna('1000').astype(int).T.values.tolist()

pprint.pprint(dn, width=300)

[[1000, 1000, 1000, 1000, 1000, 1000, 9999, 9999, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
 [1000, 1000, 1000, 1000, 7777, 7777, 9999, 9999, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
 [1000, 1000, 1000, 1000, 1000, 1000, 9999, 9999, 1000, 1000, 1000, 1000, 1000, 1000, 8888, 8888],
 [1000, 1000, 1000, 1000, 1000, 1000, 9999, 9999, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000],
 [1000, 1000, 1000, 1000, 1000, 1000, 9999, 9999, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]]